-- Drop and recreate Users table (Example)
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
<<<<<<< HEAD
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
-- Create Tables for the Database
=======
DROP TABLE IF EXISTS sells CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
-- Add users Table
>>>>>>> 34d37c9f793d1ab3c65d6326f196c29e518fd0de
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE books (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  price INTEGER NOT NULL,
  author VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  year SMALLINT NOT NULL,
  bookcover VARCHAR(255) NOT NULL
);
CREATE TABLE stores (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
  price INTEGER NOT NULL
);
CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  book_id INTEGER REFERENCES books(id) ON DELETE CASCADE
);
CREATE TABLE carts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  book_id INTEGER REFERENCES books(id) ON DELETE CASCADE
);
CREATE TABLE sales (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  store_id INTEGER REFERENCES stores(id) ON DELETE CASCADE,
  cart_id INTEGER REFERENCES carts(id) ON DELETE CASCADE,
  sold_date DATE NOT NULL,
  first_name VARCHAR(225) NOT NULL,
  last_name VARCHAR(225) NOT NULL,
  email VARCHAR(225) NOT NULL,
  phone VARCHAR(225) NOT NULL,
  shipping_address VARCHAR(225) NOT NULL,
  city VARCHAR(225) NOT NULL,
  province VARCHAR(225) NOT NULL,
  postal_code VARCHAR(225) NOT NULL
);
<<<<<<< HEAD
<<<<<<< HEAD

=======
-- CREATE TABLE messages (
--  id SERIAL PRIMARY KEY NOT NULL,
--  sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--  recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--  content TEXT NOT NULL,
-- );
>>>>>>> 34d37c9f793d1ab3c65d6326f196c29e518fd0de
=======
CREATE TABLE messages (
 id SERIAL PRIMARY KEY NOT NULL,
 sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 content TEXT NOT NULL
);
>>>>>>> d2c5ee6045a83ab1f4caf6a507b047726aa1829d
